services:
  - type: web
    name: secret-santa
    env: node
    plan: free
    region: oregon
    repo: "abisheknew/Secret_Santa"
    buildCommand: "npm install && cd web && npm install && npm run build"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
    autoDeploy: true
